<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\ExonBreak.Resources\ExonBreak.Resources.csproj"/>
        <ProjectReference Include="..\ExonBreak.Server\ExonBreak.Server.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="ppy.osu.Framework" Version="2026.513.0" />
        <PackageReference Include="Serilog" Version="4.3.2-dev-02419" />
        <PackageReference Include="Serilog.Sinks.SpectreConsole" Version="0.3.3" />
    </ItemGroup>
</Project>
